name: CI

on:
  push:
    branches: [main]
  pull_request:
  
jobs:
  ci:
    name: ⚙️ CI
    runs-on: ubuntu-latest
    steps:
      - name: 🌲 Redwood CI
        uses: redwoodjs/project-ci-action@v0.1.1
        env:
          DOMAIN_URL: "http://localhost:8910/"
